#pragma once

#define ATS_GL_EXTENSION_TEXTURE_FILTER_ANISOTROPIC "GL_EXT_texture_filter_anisotropic"
#define ATS_GL_EXTENSION_SPIR_V_SHADER_BINARIES     "GL_ARB_gl_spirv"

#define ATS_LINEAR                  0x0001 // TEXTURE_FILTERING_METHOD, FRAMEBUFFER_FILTERING_METHOD
#define ATS_NEAREST                 0x0002 // TEXTURE_FILTERING_METHOD, FRAMEBUFFER_FILTERING_METHOD, ATS_OUTPUT_FILTERING_METHOD
#define ATS_EDGE                    0x0003 // TEXTURE_FILTERING_METHOD, ATS_OUTPUT_FILTERING_METHOD

#define ATS_MIPMAP_NONE             0x0000 // ATS_MIPMAP_NEAREST
#define ATS_MIPMAP_LINEAR           0x0001 // ATS_MIPMAP_NEAREST
#define ATS_MIPMAP_NEAREST          0x0002 // ATS_MIPMAP_NEAREST

#define ATS_COORD_SYS_XYZ           0x0000 // Default coord system
#define ATS_COORD_SYS_ZYX           0x0001 // Blender coord system
